language: node_js
node_js:
  - '9'
  - '8'
  - '6'

env:
  - WEBPACK_VERSION=2 EXTRACT_PLUGIN_VERSION=2
  - WEBPACK_VERSION=3 EXTRACT_PLUGIN_VERSION=3.0.2
  - WEBPACK_VERSION=4 EXTRACT_PLUGIN_VERSION=next

matrix:
  exclude:
    - node_js: '6'
      env: WEBPACK_VERSION=next EXTRACT_PLUGIN_VERSION=next

install:
  - npm install
  - npm install webpack@$WEBPACK_VERSION extract-text-webpack-plugin@$EXTRACT_PLUGIN_VERSION || true

script:
  - npm test

after_script:
  - $(npm bin)/codecov
